name: Hello World

on:
  workflow_dispatch:

defaults:
  run: 
   shell: bash
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      - name: hello world
        run: echo '${{ toJSON(steps)}}' | jq
 
  bye:
    runs-on: ubuntu-latest
    steps:
      - name: bye world
        run: echo "Tschueees"
 
