name: Hello World

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      - name: hello world
        run: echo "Moiiiinsen"
        shell: bash
  bye:
    runs-on: ubuntu-latest
    steps:
      - name: bye world
        run: echo "Tschueees"
        shell: bash
