name: Deploy Angular Project on Github Pages

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Intsall and build
        working-directory: .
        run: npm install && npm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        width:
          branch: gh-pages
          folder: ./dist/try-git-pages/browser
